openapi: 3.0.0
info:
  title: Sample API
  description: This is a sample API description.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /questions:
    get:
      summary: Get all questions
      parameters:
        - name: categoryId
          in: query
          description: ID of the category to filter questions
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Get questions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Question'
    post:
      summary: Create a new question
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionInput'
      responses:
        '200':
          description: Create question
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
  /categories:
    get:
      summary: Get all categories
      responses:
        '200':
          description: Get categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      summary: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionInput'
      responses:
        '200':
          description: Create question
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
components:
  schemas:
    Question:
      type: object
      properties:
        id:
          type: string
        question:
          type: string
        answerId:
          type: string
        categoryId:
          type: string
        options:
          type: array
          items:
            $ref: '#/components/schemas/Option'
      required:
        - id
        - question
        - answerId
        - options
        - categoryId
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name
    Option:
      type: object
      properties:
        id:
          type: string
        value:
          type: string
      required:
        - id
        - value
    QuestionInput:
      type: object
      properties:
        question:
          type: string
        wrongAnswers:
          type: array
          items:
            type: string
        goodAnswer: 
          type: string
        categoryId:
          type: string
      required:
        - question
        - wrongAnswers
        - goodAnswer
        - categoryId
    CategoryInput:
      type: object
      properties:
        name:
          type: string
      required:
        - name